<dndUI>:
    orientation:"vertical"

    BoxLayout:
        size_hint_y:None
        Button:
            text:"run"
            on_press: root.run()
        Button:
            text:"run Today"
            on_press: root.runToday()

        Button:
            text:"run By date"

    TextInput:
        background_color: 0,0,0,1
        cursor_color: .43,.79,.213,1
        foreground_color:.43,.79,.213,1
        readonly: True
